name: Release
on:
  workflow_run:
    workflows: ['Tests']
    branches: [main]
    types:
      - completed
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Set yarn version
        run: yarn set version 3.6.2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: YarnInstaller
          author_email: devs@frigade.com
          message: "chore: yarn install"
          cwd: ./
          add: "yarn.lock"
          push: true
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
